Fix issue #121 by sending each card separately to avoid overloading a…
jasonwilliams/anki pull request #130
Opened 2024-06-19 16:38 UTC by ccammack

…nki-connect.

Before applying the fix, create a large deck as described in #121 and send it to Anki. Resending the deck a second time without any changes may trigger a disconnection error. Changing the cards using sed as desribed in #121 and resending will definitely trigger a disconnection error.

Apply the fix and repeat to see that the error no longer happens.

Please note that I bumped the version to 1.34 because 1.33 was already released.  The marketplace version acted like it was out of date even though the version said 1.3.3.

2024-06-20 10:34 UTC, jasonwilliams commented
Thanks, appreciated. I will try and read through the issue and take a look when I have some time.

2024-06-28 08:58 UTC, jasonwilliams requested changes
Ok I've been taking a look at this issue, so my understanding here is we're calling updateFields inside a promise.all so its trying to update all cards in parallel. I assume there's only so many connections that ankiConnect can handle at a time (5 in this case) so the 6th one just doesn't get accepted at all.

It seems that [`addNotes`](https://github.com/jasonwilliams/anki/blob/main/src/AnkiService.ts#L124-L138) is unaffected because we batch send those so its only a single connection.

My advice here would be to update the [`_pushUpdatedCardsToAnki`](https://github.com/jasonwilliams/anki/blob/main/src/models/Deck.ts#L115-L117) function rather than the code that calls into it. Otherwise this bug could happen again from another part of the codebase.

As mentioned above, `pushNewCardsToAnki` doesn't need to be wrapped in a for loop because it already batches (see link above).

> Please note that I bumped the version to 1.3.4 because 1.3.3 was already released. The marketplace version acted like it was out of date even though the version said 1.3.3.

If you update the version you need to update both the lock file and the package.json file too. This PR just updates the lock

2024-06-28 12:13 UTC, ccammack commented
Actually, I have switched to Emacs to manage my decks and am not willing to spend any more time on this. It sounds like you have a good fix in mind so I'll go ahead and close this request. Thanks for looking at it.

2024-06-28 12:13 UTC, closed without merging

2024-06-30 20:40 UTC, jasonwilliams commented
> Actually, I have switched to Emacs to manage my decks and am not willing to spend any more time on this. It sounds like you have a good fix in mind so I'll go ahead and close this request. Thanks for looking at it.

@ccammack thats a shame, thanks for the contributions anyway, is this emacs org mode you're referring to? Was you using emacs before?

2024-06-30 20:56 UTC, ccammack commented
Yes, but I just started looking for ways to edit decks and found a package called anki-editor that does what I need in org mode.